LAMBDA = 'λ'
STOP_STATE = '!'

MOVE_LEFT = 'L'
MOVE_NONE = 'N'
MOVE_RIGHT = 'R'

SUCCESSFUL_STATUS = "successful"
MAX_ITERATIONS_REACHED_STATUS = "max iterations reached"
MAX_ITERATIONS = 9999

NORMAL_MODE = "normal"
BY_STEP_MODE = "by step"
